//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionProcess
    {
        public System.Guid CollectionProcessID { get; set; }
        public string ImgUrl { get; set; }
        public string CollName { get; set; }
        public Nullable<System.DateTime> CollDate { get; set; }
        public string Marget { get; set; }
        public string RealName { get; set; }
    }
}
